@startuml Horario
class Horario {
    - String ccEst
    - Materia[] materias

    + Horario(int tam)
    + GettersSetters()
    + validaciones()
    + addMateria(Materia sub)
    + mostrarHorario()
}
@enduml