@startuml Materia
class Materia {
    - String dia
    - String codigoMateria
    - String nombreMateria
    - String grupo
    - int credito
    - String horario
    - String lugar
    - Docente docente
}
@enduml